repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format (poetry, autofix)
        entry: poetry run ruff format flask_more_smorest tests
        language: system
        types: [python]

      - id: ruff-lint
        name: ruff lint (poetry, autofix)
        entry: poetry run ruff check --fix flask_more_smorest tests
        language: system
        types: [python]

      - id: mypy
        name: mypy (poetry)
        entry: poetry run mypy flask_more_smorest
        language: system
        pass_filenames: false

      - id: bandit
        name: bandit (poetry)
        entry: poetry run bandit -r flask_more_smorest
        language: system
        pass_filenames: false
