repos:
  - repo: local
    hooks:
      - id: black
        name: black (poetry, autofix)
        entry: poetry run black flask_more_smorest tests
        language: system
        types: [python]

      - id: isort
        name: isort (poetry, autofix)
        entry: poetry run isort flask_more_smorest tests
        language: system
        types: [python]

      - id: flake8
        name: flake8 (poetry)
        entry: poetry run flake8 flask_more_smorest tests
        language: system
        types: [python]

      - id: mypy
        name: mypy (poetry)
        entry: poetry run mypy flask_more_smorest
        language: system
        pass_filenames: false

      - id: bandit
        name: bandit (poetry)
        entry: poetry run bandit -r flask_more_smorest
        language: system
        pass_filenames: false
